# @package _global_
loss:
  xyz_3d:
    enabled: true
    weight: 1.0
    normalize_by_mean_depth: true
    use_signed_log: true
  uv_2d:
    enabled: true
    weight: 0.1
  visibility:
    enabled: true
    weight: 0.1
  displacement:
    enabled: true
    weight: 0.1
  normal:
    enabled: true
    weight: 0.4
  confidence:
    enabled: true
    weight: 0.2
    confidence_weights_xyz_error: true
    confidence_target:
      enabled: false
      weight: 0.2
  reprojection_uv_from_xyz:
    enabled: false
